### PR TITLE
Hexo 6.0.0

### PR DESCRIPTION
**Pull request by tomap**
Following the breaking change on list_tags, I propose to release a v6 of Hexo
cf https://github.com/hexojs/hexo/commit/042f86294691f7a18ab27b853dd7066d6aed1408

I checked, and this was the only commit to release v5:  https://github.com/hexojs/hexo/commit/14890743dd00e1a1e7c4bd9c7ef632f609d35a4c

I would also suggest to update all dependencies that are not yet updated before releasing v6 (devDependencies)

Anyone wanted to add something to the v6 ?

We should also prepare a blog post to announce the release :)

### CODE REVIEW

**Review by yoshinorin — COMMENTED** [review]
How about drop Node 10.x?

> https://github.com/hexojs/hexo/issues/4378

IMHO we should start to drop Node.js 10.x from all repos.

**Comment by SukkaW** [comment]
I will mark this pr as a proposal. Obviously, it is an opportunity for us to introduce many other breaking changes as well.

**Comment by stevenjoezhang** [comment]
I would suggest to migrate from commonjs to esm in Hexo 6. All dependent packages created by [Sindre Sorhus](https://github.com/sindresorhus) require esm to load.

**Comment by tomap** [comment]
@stevenjoezhang I also think we should do that, but this project will clearly take longer than Sept 18th, so I would recommend doing that in Hexo 7

**Comment by stevenjoezhang** [comment]
OK, I replied here as a to-do list https://github.com/hexojs/hexo/issues/4378#issuecomment-914165037

**Comment by SukkaW** [comment]
> > I will mark this pr as a proposal. Obviously, it is an opportunity for us to introduce many other breaking changes as well.
> 
> FYI, I am currently working on replacing RegExp with the state machine for escaping (in `backtickcode` filter and in post render).

#4780

**Comment by SukkaW** [comment]
Some other PRs and proposals I'd like to included in the Hexo 6.0.0:

- #4771
- #4781
- #4782

**Comment by tomap** [comment]
Could we create v6.0, even without https://github.com/hexojs/hexo/pull/4781 that would allow us to have a fix for the security issue released recently

**Comment by yoshinorin** [comment]
@tomap @SukkaW 
Should we merge this PR and release the `v6.0.0`? 
Sorry, I don't know we should publish it or not...

If yes, I can publish a new version.

**Comment by tomap** [comment]
I'm ok with it. We need to prepare an announcement on site also? Before?

**Review by yoshinorin — APPROVED** [review]

**Comment by yoshinorin** [comment]
> I'm ok with it. We need to prepare an announcement on site also? Before?

I think after is enough.

**Comment by yoshinorin** [comment]
@hexojs/core 
Done.
I just published the new version.

> https://www.npmjs.com/package/hexo/v/6.0.0
> https://github.com/hexojs/hexo/releases/tag/6.0.0

**Comment by yoshinorin** [comment]
> Also, we need to address some kind of breaking changes migration guideline for the fix.

Does someone please let me know about migration guideline?
Or would you please edit [v6.0.0 release note](https://github.com/hexojs/hexo/releases/tag/6.0.0)?

**Pull request merged**
