### PR TITLE
Better tracing on error

### PR DESCRIPTION
**Pull request by leesei**
Thank you for creating a pull request to contribute to Hexo code! Before you open the request please review the following guidelines and tips to help it be more easily integrated:

- [x] Add test cases for the changes.
- [x] Passed the CI test.

### CODE REVIEW

**Comment by leesei** [comment]
Implements the long awaited Nunjuck error context dump
https://github.com/hexojs/hexo/issues/1771#issuecomment-187583293

**Comment by JLHwung** [comment]
Great job. Please add unit test on `formatNunjucksError`. Integration test with hexo engine is also good to do.

**Comment by leesei** [comment]
I tried to add test on `hexo.render.render()` but faced with these problems:
1. Is there any difference with `render()` and `renderSync()`? [This page](https://hexo.io/api/tag) says Hexo 3 uses Nunjunks for async rendering.
2. I have to specify `swig` as engine to get tag plugins to be parsed. Aren't we using Nunjunks?
3. I cannot register tag.

See code in [this gist](https://gist.github.com/leesei/6bdad2b7b70d250c1d76582bda9d318a).

**Comment by leesei** [comment]
For unit test of `formatNunjucksError()`, I'll have to expose this function to the `module.export`?

**Comment by leesei** [comment]
@hexojs/core Test added, please review.
Coverall's report is contradictory, there should not have been an decrease.
I don't Codeclimate's rule is absolute.

**Comment by leesei** [comment]
Ping @JLHwung @segayuu. Any comments?

**Comment by NoahDragon** [comment]
The code LGTM.

**Pull request merged**
