### PR TITLE
chore(deps): bump hexo-util to 1.6.1

### PR DESCRIPTION
**Pull request by SukkaW**
## What does it do?

- update hexo-util to 1.6.1.
- include #3847 (with new `isExternalLink()`)
- update test case for `url_for`
- The test cases for `url_for()`, `full_url_for()` with `pretty_urls` configuration.

## How to test

```sh
git clone -b hexo-util-1.6 https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

## Pull request tasks

- [ ] Add test cases for the changes.
- [x] Passed the CI test.

### CODE REVIEW

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo-util/pull/143 to be released in https://github.com/hexojs/hexo-util/pull/144

**Comment by SukkaW** [comment]
The test cases for `url_for()`, `full_url_for()` with `pretty_urls` configuration is now bring up.

**Comment by SukkaW** [comment]
The benchmark result:

| | Node.js 8 | Node.js 10 | Node.js 12 | Node.js 13 |
|:---:|:---:|:---:|:---:|:---:|
| Current master branch | 37.8s | 33.8s | 83.7s | 87.5s |
| This PR | 25.6s | 24.8s | 25.5s | 26.2s |
| PR #3834 | 27s | 27s | 27s | 26s |

The performance regression is now solved.

**Comment by curbengh** [comment]
@SukkaW 
please rebase your other PRs as well.

**Pull request merged**
