### PR TITLE
feat: meta_generator helper

### PR DESCRIPTION
**Pull request by SukkaW**
## What does it do?

This is a continuation of #3669 

## How to test

```sh
git clone -b meta_generator https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

## Pull request tasks

- [x] Add test cases for the changes.
- [x] Passed the CI test.

### CODE REVIEW

**Comment by curbengh** [comment]
What's the benefit of having this instead of `meta_generator: true|false`?

**Comment by SukkaW** [comment]
@curbengh 
If a theme want to add `meta_generator` tag this helper will be helpful. With theme using this helper, the `meta_generator` filter can be disabled and speed up generation.

**Comment by curbengh** [comment]
Fair enough.

Then,

https://github.com/hexojs/hexo/blob/3a3e101d80599b2976133af7478c5e0a5222f52e/lib/plugins/filter/after_render/meta_generator.js#L8

can be refactored to `const hexoGeneratorTag = metaGeneratorTag();` to de-duplicate.

**Comment by SukkaW** [comment]
@curbengh Since it is only a simple string, I see no necessary replacing it with a function.

**Pull request merged**
