### PR TITLE
fix relative_url reference

### PR DESCRIPTION
**Pull request by dranovsk**
fix for "TypeError: this.relative_url is not a function" error, issue #2426

Thank you for creating a pull request to contribute to Hexo code! Before you open the request please review the following guidelines and tips to help it be more easily integrated:

- [ ] Add test cases for the changes.
- [ ] Passed the CI test.

### CODE REVIEW

**Comment by seaoak** [comment]
Thank you for the PR!

I'm sorry, but I think that, if this patch is necessary, other helper functions should be modified in the same manner.

`this.relative_url()` is a common way to call other helper function in a helper function:

- https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/css.js#L16
- https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/date.js#L47
- https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/favicon_tag.js#L4

So I think that the issue #2426 is not caused by the `url_for()` itself.  Rather, it would be caused by the way to call the `url_for()`.  We might need to correct `lib/models/post.js`.

**Comment by NoahDragon** [comment]
@seaoak Thanks for pointing this out. 

@dranovsk Have you reproduced the  #2426 issue, and this fix resolved it?

**Comment by seaoak** [comment]
I found a solution for the issue #2426, but it's a bit *hacky*.

```
$ git checkout HEAD~
$
$ git log -1 --oneline | cat
e54f5e1 Update package.json
$
$ vi lib/models/post.js
$
$ git diff | cat
diff --git a/lib/models/post.js b/lib/models/post.js
index c14afb0..cf83a33 100644
--- a/lib/models/post.js
+++ b/lib/models/post.js
@@ -55,9 +55,9 @@ module.exports = function(ctx) {
   });

   Post.virtual('permalink').get(function() {
-    var url_for = ctx.extend.helper.get('url_for');
+    var self = _.assign({}, ctx.extend.helper.list(), ctx);
     var config = ctx.config;
-    var partial_url = url_for.call(ctx, this.path);
+    var partial_url = self.url_for(this.path);
     return config.url + _.replace(partial_url, config.root, '/');
   });
$
```

I found that only `lib/models/post.js` calls `ctx.extend.helper.get()` directly in the `hexo` package.  So I just have to correct `lib/models/post.js`.

I referred to `lib/theme/view.js` which enables helper functions in the context of its subroutines (such as `render()`).

Do you have better idea?

**Comment by NoahDragon** [comment]
@seaoak Excellent! Thanks for digging into this issue. Let me have a look first. I will come back to you.

**Comment by NoahDragon** [comment]
@seaoak I think you are right. I will revert this PR, and create new PR regarding your suggestion.

**Pull request merged**
