### PR TITLE
chore(deps): update warehouse requirement from ^2.2.0 to ^3.0.0

### PR DESCRIPTION
**Pull request by YoshinoriN**
> hexojs/warehouse#61

### CODE REVIEW

**Comment by YoshinoriN** [comment]
Test failure caused by this [commit](https://github.com/hexojs/warehouse/commit/c67c80b1921071d46909466bd91c6f78be2763f1)

Now I'm investigating.

**Comment by YoshinoriN** [comment]
Caused by [this change](https://github.com/hexojs/warehouse/pull/19/files/b203b7c7a7178e46146ac3d7e02d8e17eea5a6e4#diff-a140b60b6a99a8c69f4b5d0d1f1f2bfaR333).

Now I'm asking it to @segayuu. We might have to release the warehouse `v3.0.1`

**Comment by curbengh** [comment]
My guess is that promise might have resolved/rejected prematurely,

https://github.com/hexojs/hexo/blob/6cda2021e384b4ddd4cf1e6fd3cc8b878094c5dc/test/scripts/box/box.js#L129-L149

what about,
``` js
return Promise.all[fs.writeFile(path, 'a')].then(() => {
      box.Cache.insert({
        _id: cacheId,
        modified: 0
      })
    ])}
```

---

https://github.com/hexojs/hexo/blob/6cda2021e384b4ddd4cf1e6fd3cc8b878094c5dc/test/scripts/box/box.js#L151-L168

``` js
return Promise.all[fs.writeFile(path, 'a')].then
```

**Comment by YoshinoriN** [comment]
@curbengh 
Thanks for your support 😃 
But, it seems caused by `modified` fields type. The `modified` field seems should use `UnixTime` but current source code mixed `UnixTime` and `ISO8601`

I create new PR (#3739 )

**Comment by YoshinoriN** [comment]
Today, I wrote my blog using by this branch. It seems no-problem.

**Pull request merged**
