### PR TITLE
Update dependencies & fix eslint issues

### PR DESCRIPTION
**Pull request by tomap**
Hi, 

I updated dependencies, added a badge to check them and fix some eslint issues
TODO: still some eslint issues
And, locally, I had a crash during tests, but the crash did not occurred in all run

```
 1) Hexo
       Box
         Box
           watch() - create:
     TypeError: Cannot read property '0' of undefined
      at box.watch.then.delay.then (test/scripts/box/box.js:261:35)
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:638:18)
      at Promise._resolveCallback (node_modules/bluebird/js/release/promise.js:432:57)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:524:17)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:638:18)
      at Timeout._onTimeout (node_modules/bluebird/js/release/timers.js:26:46)
```

- [ Y] Add test cases for the changes.
- [ X] Passed the CI test.

### CODE REVIEW

**Comment by tomap** [comment]
Hi,
The tests seem to work on TravisCI.
All there is to do is to fix the last eslint issues.
And investigate the coverage decrease.

If I do this, will you consider merging this PR ?

Thank you

**Comment by NoahDragon** [comment]
I saw may file changes are code style. Could you please elaborate more about the changes on fix eslint issues?

**Comment by tomap** [comment]
I fixed most of those issues using ```eslint --fix```
For the manual stuff: 
- some were variable declaration that had to be separated by comma:
```
var a;
var b;
```
should be:
```
var a;
var b;
```
See https://github.com/hexojs/hexo/pull/2908/files#diff-cfaf136b2e60bbf3769efc2a9c11c453

I also skipped the rule for regex in some cases in fear of breaking something:
https://github.com/hexojs/hexo/pull/2908/files#diff-f9e8cb097646a10f8348a5e313fbaa14

There are still some stuff to fix manually. I created the PR without fixing everything to have the results from CI sooner & maybe someone will want to finish the manual fixes :)

**Comment by tomap** [comment]
I fixed the coverage issue (see https://github.com/hexojs/hexo/pull/2908/commits/903cb2afa5868cdf18d5d3be0abdc3f94ed9dc3f ). there are now only 2 remaining eslint issues: 
```
/home/travis/build/hexojs/hexo/lib/hexo/index.js
  350:58  error  Function expected a return value  array-callback-return
/home/travis/build/hexojs/hexo/lib/plugins/processor/post.js
  168:18  error  Function expected a return value  array-callback-return
```
I'm unsure how to fix those:
```
// index.js
 .map(function(item) {
      if (typeof item !== 'object' || item.path == null) return;
```
and 
```
// post.js
}).map(function(item) {
      var id = pathFn.join(assetDir, item).substring(baseDirLength).replace(/\\/g, '/');
      var asset = PostAsset.findById(id);
      if (asset) return;
```

Should I return false, ignore the warning or else?

Thank you

**Comment by JLHwung** [comment]
@tomap You can simply `return undefined` to make eslint happy. 😄

**Comment by tomap** [comment]
Done. I kept the other change somewhere else and will create another PR once this one is merged :)

**Pull request merged**
