### PR TITLE
update build matrix

### PR DESCRIPTION
**Pull request by tomap**
This PR adds nodejs 10 as well as 11
node 10 will become the next lts
node 9 was an intermediate release

and add tests on linux for appveyor

See https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/#running-windows-and-linux-builds-side-by-side

and 

https://github.com/nodejs/Release#release-schedule

### CODE REVIEW

**Comment by YoshinoriN** [comment]
@tomap 
AppVeyor support Node.js v11 on [2018-11-09](https://www.appveyor.com/updates/2018/11/09/).
IMHO we should merge this PR, if will pass at AppVeyor.

But, AppVeyour seems [not support trigger (manually) build other than default branch](https://github.com/appveyor/ci/issues/2253).

**Comment by YoshinoriN** [comment]
PS

So, I thinks we have to re-push this PR something way. For example `git rebase` & `force push`.

**Comment by tomap** [comment]
Yes, I noticed. I will rebase asap

**Comment by tomap** [comment]
Ok, I'm done. be sure to squash the result when merging!
I had to change a line about the installation/update of nodejs
I removed the test regarding linux support on appveyor because it was not working. I'll try to do another PR for that

**Pull request merged**
