### PR TITLE
[helper] add log()

### PR DESCRIPTION
**Pull request by leesei**
Good for logging objects in theme and plugin

 Changes to be committed:
	modified:   lib/plugins/helper/debug.js
	modified:   lib/plugins/helper/index.js

### CODE REVIEW

**Comment by Xuanwo** [comment]
Add more coverage test?

**Comment by leesei** [comment]
K, but I think I can only asset true for the `serverLog()` test.

**Comment by tommy351** [comment]
The name `serverLog` does not make sense. This helper just called `console.log`.

**Comment by leesei** [comment]
That's to distinguish between printing `script` and calling browser's
`console.log()`
I used to have the latter function but not finding it very useful.

What's your take on the name?

BTW, can I detect `serve` and `generate` command in helper? I thinking
about automatically disabling this function in commands other than `server`.

**Comment by tommy351** [comment]
If you only want to enable this helper in the server. You should move this helper to https://github.com/hexojs/hexo-server

**Comment by tommy351** [comment]
And I think `log` or `print` would be a better name for this helper.

**Comment by leesei** [comment]
I don't think we can get the server object or call its function in templates, right?

I'll close this PR and reopen a new one with test.

**Pull request closed without merging**
