### PR TITLE
fix: Global asset folder not working when source dir is changed  another path

### LINKED ISSUE #3398: Global asset folder not working when source dir is changed another path
## Environment Info

Node version(`node -v`):v8.12.0

Your site `_config.yml` (Optional): default

Your theme `_config.yml` (Optional): default

Hexo and Plugin version(`npm ls --depth 0`): default

## For BUG

When I changed the config `source` value to `../source`,the source images can't be generated.Here is the config:

```yaml
source_dir: ../source
```

You can run: 

```bash
hexo new test
cd ../source
mkdir images
# copy a example image to images
hexo generate
```

The images folder can not be generated.

### PR DESCRIPTION
**Pull request by xiaomingplus**
fix #3398

Thank you for creating a pull request to contribute to Hexo code! Before you open the request please review the following guidelines and tips to help it be more easily integrated:

- [ ] Add test cases for the changes.
- [ ] Passed the CI test.

### CODE REVIEW

**Comment by xiaomingplus** [comment]
Any one can review this?

**Comment by YoshinoriN** [comment]
Sorry, We have many repositories and need to maintain them.
Would you please wait patiently ? Thanks :relaxed:

**Comment by YoshinoriN** [comment]
@xiaomingplus 
It's so sorry, very late reply...
I think this issue caused by https://github.com/hexojs/hexo/issues/3410

I would be grateful if you re-create PR about fix https://github.com/hexojs/hexo/issues/3410.
Thanks :)

**Comment by xiaomingplus** [comment]
@YoshinoriN it's can be reviewed now.I add a unit test for this change.

**Comment by YoshinoriN** [comment]
@xiaomingplus 
Thanks :)
I will check it PR this weekend.

**Comment by YoshinoriN** [comment]
@xiaomingplus 
I tested this locally & works well. LGTM :)

Just to be sure, is this problem is [global asset floder](https://hexo.io/docs/asset-folders#Global-Asset-Folder)'s problem. correct?

If yes, would you please change your issue & PR title? I think it is better "global asset folder" words  include in the title.

**Comment by xiaomingplus** [comment]
@YoshinoriN yep, I have changed the title.

**Comment by YoshinoriN** [comment]
Merged!!
Thank you for your contribution :)

**Pull request merged**
