### PR TITLE
release: 5.3.0

### PR DESCRIPTION
**Pull request by stevenjoezhang**
Fix https://github.com/hexojs/hexo/issues/4594

```
## Changes

- fix(load_plugins): ignore plugin whose name is started with "hexo-theme" @stevenjoezhang [#4592]
- Replace `process.mainModule` with `require.main` @stevenjoezhang [#4583]
- expose `escape_html` helper method for string manipulation to templates @awwong1 [#4581]
- list_tags: span element & custom class for label @noraj [#4578]
- fix(codeblock): closing code fence may be followed only by spaces @stevenjoezhang [#4574]
- docs(badge): replace david-dm with more reliable shields.io @curbengh [#4538]
```

### CODE REVIEW

**Comment by SukkaW** [comment]
It is not required to update minor or patch version if there is no `packages-lock.json` specified. npm will install the latest major version automatically.

**Review by SukkaW — APPROVED** [review]

**Comment by SukkaW** [comment]
Is the changelog ready?

**Comment by SukkaW** [comment]
Since https://github.com/hexojs/hexo/pull/4578 introduces a new feature, I would suggest bumping a minor version instead of a patch version. Hexo 5.3.0 would be fine.

**Review by SukkaW — APPROVED** [review]

**Review by YoshinoriN — APPROVED** [review]

**Comment by YoshinoriN** [comment]
Done :)

> https://www.npmjs.com/package/hexo/v/5.3.0

**Pull request merged**
