### PR TITLE
Fix match attribute in pre tag when render hexo tag

### PR DESCRIPTION
**Pull request by popomore**
Thank you for creating a pull request to contribute to Hexo code! Before you open the request please review the following guidelines and tips to help it be more easily integrated:

- [x] Add test cases for the changes.
- [ ] Passed the CI test.

Relate https://github.com/hexojs/hexo/pull/2578#issuecomment-303488253

### CODE REVIEW

**Comment by seaoak** [comment]
This new regexp still marks *any* `<code>` element as a target which will be escaped, regardless whether it is wrapped by a `<pre>` element or not.  So, why can we not use simpler regexp such as follows?

```
/<code.*?>([\s\S]*?)<\/code>/
```

**Comment by stevenjoezhang** [comment]
Any updates on this thread?

**Comment by SukkaW** [comment]
@stevenjoezhang IMHO, the fix here is unnecessary.

Hexo only highlight code with `code()` tag and `backtick_code_filter`. Markdown renderer only wrapped code block inside `<pre><code>` (which means no attribute will be added to `<pre>` tag during post rendering process).

However, since `code()` is a tag helper while `backtick_code_filter` already escaped swig tag, there is no need for this fix then.

**Comment by stevenjoezhang** [comment]
I researched these related issues, and one reason for the problem is the use of `{% raw %}` tags. This PR can be considered to be superseded by https://github.com/hexojs/hexo/pull/3459.

**Pull request closed without merging**
