### PR TITLE
refactor(external_link): utilize hexo-util isExternalLink()

### PR DESCRIPTION
**Pull request by SukkaW**
## What does it do?

This is a performance test of https://github.com/hexojs/hexo-util/pull/124 to see if #3839 is still necessary. If newer `isExternalLink()` works, #3839 should be superseded by #3835.

## How to test

```sh
git clone -b test-utilize-hexo-util https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

## Pull request tasks

- [ ] Add test cases for the changes.
- [x] Passed the CI test.

### CODE REVIEW

**Comment by SukkaW** [comment]
- Node.js 10 `27s`
- Node.js 12 `30s`
- Node.js 12 `28s`

Emmmm, I think it is still necessary to have #3839 then.

**Comment by curbengh** [comment]
> Emmmm, I think it is still necessary to have #3839 then.

#3839 is duplicate of https://github.com/hexojs/hexo-util/pull/124, so https://github.com/hexojs/hexo/pull/3835 is necessary, otherwise it defeats the purpose of https://github.com/hexojs/hexo-util/pull/119.

**Comment by SukkaW** [comment]
@curbengh Yeah. So I need to find out what cause the difference between #3839 and https://github.com/hexojs/hexo-util/pull/124.

**Comment by curbengh** [comment]
My guess is that there is a possibility that hexo-util@1.5.0 is still used because it's installed by dependency as sub-dependency.

**Comment by SukkaW** [comment]
@curbengh Currently, the only difference between #3839 and https://github.com/hexojs/hexo-util/pull/124 is how it handle `exclude`. #3839 converts exclude into array first, then `isExternal()` use `exclude` as an array directly. While https://github.com/hexojs/hexo-util/pull/124 still convert exclude into array every time `isExternalLink()` is called.

**Comment by SukkaW** [comment]
Rebased and it is ready for review. Should be merged after a newer version of hexo-util is released.

**Comment by SukkaW** [comment]
I think I might add extra changes to this PR.

**Comment by curbengh** [comment]
Please update thie repo's hexo-util to 1.6.0.

**Comment by curbengh** [comment]
Need to include 8ecb7822f52b8b903095de0e6a0c7ac0fd9dbea8 when updating hexo-util to 1.6.0 to pass the test.

**Comment by SukkaW** [comment]
Should be superseded by #3888

**Pull request closed without merging**
