### PR TITLE
ci(benchmark): generate flamegraph

### PR DESCRIPTION
**Pull request by SukkaW**
## What does it do?

Use `0x` to generate a human readable flamegraph after benchmark. The flamegraph directory will be under `${TRAVIS_BUILD_DIR}/0x`.

Before we could find a way to deploy the flamegraph, I will leave this PR as a draft.

## How to test

```sh
git clone -b 0x-flamegraph https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

## Screenshots

The directory structure should like this:

```
0x
├── flamegraph.html
├── isolate-0x5af5020-1756-1756-v8.log
├── isolate-0x5af5020-1756-1756-v8.log.json
├── isolate-0x5af5020-1756-1756-v8.log.preprocess-ready
└── meta.json

0 directories, 5 files
```

And the flamegraph looks like this:

image

## Pull request tasks

- [ ] Add test cases for the changes.
- [x] Passed the CI test.

### CODE REVIEW

**Comment by SukkaW** [comment]
Here is an example of deployed flamegraph: https://3d515f2857f23f6169e4b51dfa03a5ba568f3e4e-hexo.surge.sh/flamegraph.html

**Comment by curbengh** [comment]
The flamegraph can help to identify bottleneck?

**Comment by SukkaW** [comment]
@curbengh 

image

From flamegraph we can see there are three main bottleneck:

- `striptags` from `hexo-util.stripHTML`
- `highlightjs`, which we plan to bring up an alternative in Hexo 5.0.0
- `externalLinkFilter`.

**Comment by YoshinoriN** [comment]
I have a question about [surge](https://surge.sh/).
Should we delete old published documents from surge?

**Comment by SukkaW** [comment]
@YoshinoriN 

https://surge.sh/pricing

It seems that Free plan already included unlimited publish.

**Comment by YoshinoriN** [comment]
@SukkaW 
Sorry, so the late reply.
10 days ago, I asked the surge support team about this matter on their slack just in case.

> Hello :)
>
> Now we are considering to use surge.sh subdomain for publishing PullRequest benchmark.
>
> https://github.com/hexojs/hexo/pull/4000
>
> As the surge free plan, we can publish unlimitedly. If we use this way, we will publish sites (300~400 sites per/month) with surge.sh subdomain and perhaps they will never delete.
> Is this usage no-problem?

surge support team answer is `no problem at all.` :)
I will approve this PR after resolve the conflict.

**Comment by SukkaW** [comment]
@YoshinoriN I might login to `surge.sh` sometimes to remove some oldest deploys after all.

**Pull request merged**
