### PR TITLE
feat(github actions): Create tester job

### PR DESCRIPTION
**Pull request by segayuu**
## How to test

```sh
git clone -b BRANCH https://github.com/USER/hexo.git
cd hexo
npm install
npm test
```

## Pull request tasks

- [ ] Add test cases for the changes.
- [ ] Passed the CI test.

### CODE REVIEW

**Comment by segayuu** [comment]
Testing the Mac OS resulted in an error around the watch method. It can be said that the problem was discovered by this PR :)

**Comment by SukkaW** [comment]
@segayuu Well then, we could leave this PR here and dig into the macOS testing problem.

**Comment by segayuu** [comment]
Since I don't have mac OS, I can check the operation only with CI.

**Comment by SukkaW** [comment]
> Since I don't have mac OS, I can check the operation only with CI.

@segayuu It seems that all failed test cases are about `ignoring files`.

**Comment by segayuu** [comment]
Implementation around ignore file depends on `micromatch`. This error may have been caused by the implementation of `micromatch`.

**Comment by stevenjoezhang** [comment]
https://github.com/hexojs/hexo/pull/4169/checks?check_run_id=495143914#step:6:1233

截屏2020-04-26 上午9 34 02

I can reproduce three of the five failed tests on my mac. I will investigate whether more tests can be performed on `micromatch`.

**Pull request merged**
