### PR TITLE
WIP: Update test dev dependencies

### PR DESCRIPTION
**Pull request by JLHwung**
Update test devDependencies to latest, LGTM

- [ ] Add test cases for the changes.
- [x] Passed the CI test.

### CODE REVIEW

**Comment by JLHwung** [comment]
will rebase when #2849 is merged.

**Comment by NoahDragon** [comment]
I just merged #2849, please rebase if it is necessary.

**Comment by NoahDragon** [comment]
Seems like those test cases failure still haven't resolved.

**Comment by JLHwung** [comment]
Resolved by upgrading moment to 2.19.

The previous *LGTM* is possibly due to that I use `yarn` on my local development environment.

**Pull request merged**
