### PR TITLE
style: use for..of

### PR DESCRIPTION
**Pull request by SukkaW**
## What does it do?

Use `for..of` which is more clear to read, fewer lines of codes, and might be a bit faster.

## How to test

```sh
git clone -b use_for_pf https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

## Pull request tasks

- [ ] Add test cases for the changes.
- [x] Passed the CI test.

### CODE REVIEW

**Comment by segayuu** [comment]
https://jsbench.me/o2k334c1v1/1
As a result of running to the end on one site, it was about 40% slower than Classic for loop.
Personally, Classic for loop is not difficult to read. Based on this result, I do not agree with this PR.
However, since the speed does not change as much as IO processing, it may be ignored. Honest preference :)

**Comment by SukkaW** [comment]
@segayuu I don't know why `for..of` is slower in browser.

According to a benchmark run on runkit, it seems `for..of` is much more faster: https://runkit.com/sukkaw/5dd164a025808400140b9276

**Comment by curbengh** [comment]
I do agree with the classic style is easier to read as it's similar to other languages, whereas `for...of` could be confused with `for...in`.

But the node benchmark looks very convincing though, can you setup another benchmark on Node 10/12?

**Comment by curbengh** [comment]
RunKit somehow doesn't run benchmark anymore. Anyhow, I ran it using my machine:

```
Node 8.16
Run 1
for x 55.37 ops/sec ±2.81% (68 runs sampled)
for len x 49.25 ops/sec ±3.26% (63 runs sampled)
for of x 32.80 ops/sec ±2.86% (57 runs sampled)
Run 2
for x 55.17 ops/sec ±3.01% (60 runs sampled)
for len x 49.64 ops/sec ±3.03% (63 runs sampled)
for of x 31.18 ops/sec ±3.96% (55 runs sampled)
Run 3
for x 56.00 ops/sec ±2.88% (69 runs sampled)
for len x 49.54 ops/sec ±3.17% (63 runs sampled)
for of x 32.10 ops/sec ±3.28% (55 runs sampled)
```

```
Node 10.16.1
Run 1
for x 70.97 ops/sec ±2.98% (70 runs sampled)
for len x 60.21 ops/sec ±3.37% (61 runs sampled)
for of x 7.37 ops/sec ±1.16% (23 runs sampled)
Run 2
for x 71.19 ops/sec ±3.13% (70 runs sampled)
for len x 61.12 ops/sec ±3.11% (62 runs sampled)
for of x 7.34 ops/sec ±3.29% (23 runs sampled)
Run 3
for x 70.79 ops/sec ±3.13% (70 runs sampled)
for len x 60.70 ops/sec ±3.68% (62 runs sampled)
for of x 7.16 ops/sec ±3.81% (22 runs sampled)
```

**Comment by SukkaW** [comment]
@curbengh It seems unnormal. At least `for len` should be a little bit faster than `for` because array.length won't be calculated again and again.

Here is the benchmark on repl.it, and `for..of` is the slowest.

https://repl.it/repls/FavorableSqueakyProblems

```
for x 18.58 ops/sec ±5.42% (33 runs sampled)
for len x 18.76 ops/sec ±5.06% (34 runs sampled)
for of x 2.15 ops/sec ±3.69% (10 runs sampled)
```

**Comment by curbengh** [comment]
I also tried separating them into individual files, I ran again in my machine,

```
Node 10
for of x 71.67 ops/sec ±3.22% (71 runs sampled)
for of x 71.97 ops/sec ±3.24% (71 runs sampled)
for of x 66.64 ops/sec ±6.05% (60 runs sampled)
```

```
for len x 59.19 ops/sec ±6.09% (59 runs sampled)
for len x 57.70 ops/sec ±4.44% (59 runs sampled)
for len x 60.74 ops/sec ±3.19% (61 runs sampled)
```

```
for x 7.01 ops/sec ±6.44% (21 runs sampled)
for x 6.82 ops/sec ±7.52% (21 runs sampled)
for x 6.04 ops/sec ±10.92% (20 runs sampled)
```

Looks like there is a regression in Node 10.

**Comment by SukkaW** [comment]
I have rebased this branch up to latest master. Here is the benchmark result:

| | Node.js 8 | Node.js 10 | Node.js 12 | Node.js 13 |
|:---:|:---:|:---:|:---:|:---:|
| Current master branch | 29.8s | 25.6s | 24.5s | 26.6s |
| This PR | 31.5s | 26.5s | 27.3s | 27.1s |

This PR is indeed a little bit alower.

**Pull request closed without merging**
