### PR TITLE
ci(appveyor): drop appveyor

### PR DESCRIPTION
**Pull request by SukkaW**
## What does it do?

Appveyor appears to be very unstable recently, with test failed without `npm test`:

- https://ci.appveyor.com/project/tommy351/hexo/builds/33924212
- https://ci.appveyor.com/project/tommy351/hexo/builds/33924223
- https://ci.appveyor.com/project/tommy351/hexo/builds/33923413
- https://ci.appveyor.com/project/tommy351/hexo/builds/33917457

I am not sure whether it is related with npm cache or something else. But since only @tommy351 has the permission to access the Appveyor dashboard, and we are already using GitHub Action, it is about time to drop Appveyor.

cc @hexojs/core

## How to test

```sh
git clone -b ci-drop-appveyor https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

## Pull request tasks

- [ ] Add test cases for the changes.
- [ ] Passed the CI test.

### CODE REVIEW

**Comment by tommy351** [comment]
The following repositories is listed on AppVeyor dashboard currently:

- hexo-deployer-openshift
- hexo-cli
- hexo
- hexo-deployer-heroku
- hexo-server
- hexo-fs
- hexo-deployer-git

Can I remove these projects from AppVeyor? Or should I remove hexo only?

**Comment by SukkaW** [comment]
> Can I remove these projects from AppVeyor? Or should I remove hexo only?

We could remove them all. Then we will bring up GitHub Action guadually for them.

**Comment by YoshinoriN** [comment]
> IMHO you could remove them all. Then we will bring up GitHub Action for those project gradually.

+1
I agree with @SukkaW opinion.

**Comment by SukkaW** [comment]
> Please remove Appveyor badge from README.md

@YoshinoriN Done.

**Comment by tommy351** [comment]
@SukkaW Okay, I deleted all these projects on AppVeyor.

**Comment by SukkaW** [comment]
What is going on? Why Appveyor is still building the latest commit?

**Comment by tommy351** [comment]
I guess we have to remove the AppVeyor webhook on the GitHub settings page.

**Comment by curbengh** [comment]
Appveyor app is still active on hexo-util.

**Pull request merged**
