### PR TITLE
sel code block line number

### PR DESCRIPTION
**Pull request by dwatow**
as markdown begin code block:

```
   ```js   -> js code block without line number
   ```js=  -> js code block with line number, start in 1
   ```js=3 -> js code block with line number, start in 3
```

Thank you for creating a pull request to contribute to Hexo code! Before you open the request please review the following guidelines and tips to help it be more easily integrated:

- [x] Passed the CI test.
- [x] Add test cases for the changes.

### CODE REVIEW

**Comment by NoahDragon** [comment]
As line_number in config file has been used for a long while, could you please add an new configuration variable for this change?

**Comment by dwatow** [comment]
dynamic specify that do writer need line number by markdown, so doesn't need new configuration variable. thank you

**Comment by dwatow** [comment]
this is able to used "=" dynamic spcify line number, by markdown. so don't need add configuration variable, but unit test can't pass. QQ

**Comment by NoahDragon** [comment]
The errors are caused by different class name. Could you please fix it?

image

**Comment by seaoak** [comment]
I'm sorry I'm late.  I have three requests and two advices.

Request:

1. The new code *always* ignores `config.line_number`.   So existent contents depending on the configuration will be broken.  Please keep compatibility.
1. When arguments of this plugin contain a URL which includes a character `=` (such as search query for Google), the new code will not work correctly.  Please consider this situation.
1. When there are multiple arguments for this plugin and  the first argument includes a character `=`, the new code will not work correctly.  `options.firstLine` will not be a numeric string.  Second and subsequent arguments will not be used.  Please consider multiple arguments.

Advice:

1. An expression such as `cond ? true : false` is redundant.  Mostly replaceable with a simple expression `cond`.
1. Please add test cases (such as above situations).

I'm looking forward to your update! :wink:

**Comment by dwatow** [comment]
in _config.yml

```
highlight:
  enable: true
  line_number: true
  first_line_number: 'inline' # | 'always1'
```
- first_line_number
 - inline: new design
- always1: original design

**Comment by dwatow** [comment]
I have no idea about
- continuous-integration/appveyor/pr — AppVeyor build failed
- coverage/coveralls — Coverage decreased (-0.07%) to 97.082%

**Comment by dwatow** [comment]
I have no idea about [The command "npm run test-cov" exited with 1.](https://travis-ci.org/hexojs/hexo/jobs/263505454) in Travis CI, and I can't reappear error of [1) Hexo Box File stat() - callback](https://ci.appveyor.com/project/AbnerChou/hexo/build/98/job/5nu36cnnyg073jnk) in AppVeyor

**Comment by NoahDragon** [comment]
@dwatow Please ignore the error in appveyor. I will take a look the error on Travis.

**Comment by NoahDragon** [comment]
@dwatow I got your email. Sorry for the delay. I think the travis-ci is related to https://github.com/hexojs/hexo/pull/2729 . Now, the changes look good to me.

**Pull request merged**
