### PR TITLE
using Class

### PR DESCRIPTION
**Pull request by deepnum**

### CODE REVIEW

**Comment by SukkaW** [comment]
The PR looks good, but would you mind making eslint happy? It seems `L349` has broke the eslint.

**Comment by curbengh** [comment]
@deepnum 

Removing the semicolon didn't resolve it?

``` diff
- .then(locals => { route.set(path, createLoadThemeRoute(generatorResult, locals, this)); })
+ .then(locals => { route.set(path, createLoadThemeRoute(generatorResult, locals, this)) })

We would like to have this PR.

**Comment by curbengh** [comment]
@deepnum 

What happened? Do you still want to re-attempt?
We would like to have this refactor.

**Comment by curbengh** [comment]
Since this is refactor (not a bugfix), we'll re-visit after v4.

**Comment by deepnum** [comment]
You can uses lebab to automatically do this

**Comment by curbengh** [comment]
Thanks, will keep that in mind.

**Pull request closed without merging**
