### PR TITLE
skip assets of unpublished posts and delete them if exist

### PR DESCRIPTION
**Pull request by DaemondShu**
## What does it do?
Fixed issue #3478. 

## How to test

```sh
git clone -b BRANCH https://github.com/USER/hexo.git
cd hexo
npm install
npm test
```

## Screenshots
- the result before adding the unittest
image
The result is the same as the original master branch on my machine.

- the result after adding the unittest
image

- code coverage summary
image

## Pull request tasks

- [x] Add test cases for the changes.
- [x] Passed the CI test.

### CODE REVIEW

**Comment by tomap** [comment]
Hi, the build failed because of codecoverage reduction & some eslint warning. Are you able to fix those?

**Comment by MonkeyDAsce** [comment]
Thanks for your review.
I understand the eslint warning and will fix it. 
But for codecoverage, I am an nodejs beginner, is there any way to run coverage locally so that I can code and test offline?

**Comment by MonkeyDAsce** [comment]
> Thanks for your review.
> I understand the eslint warning and will fix it.
> But for codecoverage, I am an nodejs beginner, is there any way to run coverage locally so that I can code and test offline?

Oh, I found it, it's "npm run test-cov". So what's your coverage requirement? 100%, 98% or a specific num?

**Comment by tomap** [comment]
There is no coverage requirement, just that this new behavior is covered by new tests

**Comment by darekkay** [comment]
@DaemondShu thanks for providing a fix. could you please resolve the merge conflicts, so the PR hopefully gets merged? If not, I could do it and open a new PR based on this one.

**Comment by curbengh** [comment]
I've fix the merge conflict and also rebased to the latest master.

**Comment by SukkaW** [comment]
Merged, thanks!

**Pull request merged**
