### PR TITLE
Revert "Fix parsing error about <code> tag (Issue #2563)"

### PR DESCRIPTION
**Pull request by NoahDragon**
Reverts hexojs/hexo#2568

### CODE REVIEW

**Comment by NoahDragon** [comment]
@seaoak I'm reverting the changes in #2461 and #2568 for a hotfix. Could you please help me review and approve the changes?

**Comment by popomore** [comment]
Why do you revert these commit? Is there any bug exist?

**Comment by popomore** [comment]
I try to look at the vue issue tomorrow, it seems still broken.

**Comment by NoahDragon** [comment]
@popomore Yes, although reverting the #2568 could fix the generating error, the parsing error https://github.com/hexojs/hexo/issues/2575 would remain.

**Comment by popomore** [comment]
Vue is using `raw` tag in markdown, I don't know wheter it is a suitable usage.

https://github.com/vuejs/vuejs.org/blame/master/src/v2/guide/render-function.md#L556

And I found `<pre v-if="!result.staticRenderFns.length"><code>{{ result.staticRenderFns }}</code></pre>` which is not matched by our regexp, so the [assertion](https://github.com/hexojs/hexo/blob/master/lib/extend/tag.js#L62) throws.

**Comment by popomore** [comment]
If I change it to `(<pre.*?>)?<code.*?>([\s\S]*?)<\/code>(<\/pre>)?/`, and it works.

**Comment by seaoak** [comment]
I agree this simple reverting.  These two patches **break** existing user's build.  I think that first priority shuld be given to wind down user's confusion.

By user's responses, it is revealed that we did't know the precise impact of these patches.  So I think that we should not add any modification to this function until we understand this function more precisely (and add enough test cases for compatibility).

**Comment by seaoak** [comment]
Question:

In general, when we make a new release of a product, it is important whether a user's build depending on a latent bug should be kept or be subject to modification.

I basically think that a *minor* release should not break such a build.  At least both changelogs and appropriate error messages are necessary.  This is because users may think it as a regression and become distrustful of the product.  Of course, there are exceptions like a security fix.

Are there policies for such a decision in Hexo?

**Comment by NoahDragon** [comment]
@seaoak As far as I know, we don't have a strict policy on version releases. But I agree with you, we should test our program more carefully before release it to public.

**Pull request merged**
