### PR TITLE
release: 5.4.0

### PR DESCRIPTION
**Pull request by stevenjoezhang**
## What does it do?

```
## Changes

- feat: handle config.root is not exist @jiangtj [#4616]
- fix(codeblock): match whitespace but not newlines @stevenjoezhang [#4625]
- fix(i18n): page.lang is undefined when using the key `language` in front-matter @stevenjoezhang [#4614]
- github: update actions/setup-node action to v2 @stevenjoezhang [#4604]
- chore/ci: migrate from probot/stale to GitHub Actions @stevenjoezhang [#4598]
- fix(box): set property awaitWriteFinish for chokidar filewatcher

## Breaking change

- fix(excerpt): use span instead of anchor element for better SEO performance @stevenjoezhang [#4627]

## Dependencies

- chore(deps): bump js-yaml from 3.14.1 to 4.0.0 @dependabot-preview [#4607]

```

## How to test

```sh
git clone -b BRANCH https://github.com/USER/hexo.git
cd hexo
npm install
npm test
```

## Pull request tasks

- [ ] Add test cases for the changes.
- [ ] Passed the CI test.

### CODE REVIEW

**Review by SukkaW — DISMISSED** [review]

**Review by SukkaW — COMMENTED** [review]
I vote yes for the release.

BTW, have you create a PR at `hexo/site`?

**Review by YoshinoriN — APPROVED** [review]

**Comment by YoshinoriN** [comment]
Should I release soon??

**Comment by stevenjoezhang** [comment]
I would like to merge https://github.com/hexojs/hexo/pull/4633 first and rebase this pull request

Some tests failed on GitHub actions https://github.com/hexojs/hexo/actions/runs/526160247 but it is normal on my mac, so I need some time to investigate

**Comment by YoshinoriN** [comment]
I re-run GitHub actions, but two tests weren't finished even after 30min.

> https://github.com/hexojs/hexo/runs/1822811363

Not sure, but I think this problem perhaps GitHub actions problem.

**Comment by stevenjoezhang** [comment]
@yoshinorin The test passed after disabling the cache. I think it's now ready to release a new version.

**Review by yoshinorin — APPROVED** [review]

**Pull request merged**
