### PR TITLE
add mark option to code blocks

### PR DESCRIPTION
**Pull request by greg-js**
#1756 

Not sure if this is a good enough implementation but I just wanted it for my own blog and figured I'd share, feel free to close the PR if you don't like the style or think it's an unnecessary feature.

### CODE REVIEW

**Comment by lotabout** [comment]
@greg-js I believe that we still need to patch the `highlight` function in hexo-util to make it work, is that right?

About your implementation,  I think the resulting value of `mark` should contain the ranges such as `[2,4,[6,8]]` instead of expand them into `[2,4,6,7,8]`. The concern is that expanding them may result into a very long list.

**Comment by greg-js** [comment]
That's right and I submitted a PR on hexo-util as well actually.

As for your concern, I hadn't considered that. For my own blog this isn't
an issue, but if there is more interest in this, I will take a look at
doing it in a different way. I'm soon to leave on a week long trip to Spain
soon though so it'd probably be after I come back unless I find time
tomorrow

**Comment by leesei** [comment]
Merged. Thanks.

**Comment by leesei** [comment]
@tommy351 I've updated landscape, please update `hexo-starter`

**Pull request closed without merging**
