### PR TITLE
feat: add url_for and full_url_for tag plugins

### PR DESCRIPTION
**Pull request by D-Sketon**
## What does it do?

see #4749

## Pull request tasks

- [x] Add test cases for the changes.
- [x] Passed the CI test.

### CODE REVIEW

**Review by Govthub — COMMENTED** [review]
Drop your WhatsApp or telegram so we can handle it

**Comment by yoshinorin** [comment]
@D-Sketon 
Sorry, I made mistake...
https://github.com/hexojs/hexo/pull/5178 does not satisfy [CI](https://github.com/hexojs/hexo/actions/runs/4582499781/jobs/8448870647). We need fix TS2544 first.

**Comment by D-Sketon** [comment]
> @D-Sketon Sorry, I made mistake... #5178 does not satisfy [CI](https://github.com/hexojs/hexo/actions/runs/4582499781/jobs/8448870647). We need fix TS2544 first.

should #5202 be merged?

**Comment by yoshinorin** [comment]
@D-Sketon 
Thank you :)
I didn't notice that. Just now I merged #5202

**Comment by D-Sketon** [comment]
> LGTM 🚀
> 
> Would you please submit a documentation DraftPR to https://github.com/hexojs/site after merge this?

I have submited a PR https://github.com/hexojs/site/pull/2022 😀

**Pull request merged**
