### PR TITLE
release: 5.0.0

### PR DESCRIPTION
**Pull request by SukkaW**
## What does it do?

Release 5.0.0.

## How to test

```sh
git clone -b 5.0.0 https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

-----

Pending deps:

- [x] hexo-cli 4.0.0: https://github.com/hexojs/hexo-cli/pull/195 (circular dependency)
- [x] hexo-log 2.0.0: released and updated
- [x] hexo-util 2.1.0: better to have a 2.2.0 released to include latest changes (https://github.com/hexojs/hexo-util/pull/221)
- [x] hexo-renderer-marked 3.0.0: released and updated

Pending PR:

- [x] https://github.com/hexojs/hexo/pull/4420
- [x] https://github.com/hexojs/hexo/pull/4418
- [x] https://github.com/hexojs/hexo/pull/4414
- [ ] https://github.com/hexojs/hexo-starter/pull/37 (circular dependency)

Pending documents:

- [x] https://github.com/hexojs/site/issues/1447 => https://github.com/hexojs/site/pull/1451
- [x] https://github.com/hexojs/site/issues/1446 => https://github.com/hexojs/site/pull/1453
- [x] https://github.com/hexojs/site/issues/1342 => https://github.com/hexojs/site/pull/1477
- [x] https://github.com/hexojs/site/pull/1319 => https://github.com/hexojs/site/pull/1319
- [x] https://github.com/hexojs/hexo/pull/4370 => https://github.com/hexojs/site/pull/1471
- [x] https://github.com/hexojs/hexo/pull/4371 (Should be mentioned in release note)
- [ ] ~~https://github.com/hexojs/hexo/pull/4073~~
- [x] https://github.com/hexojs/hexo/pull/4119 => https://github.com/hexojs/site/pull/1454
- [x] https://github.com/hexojs/hexo/pull/4174 => https://github.com/hexojs/site/pull/1478
- [x] https://github.com/hexojs/hexo/pull/4266 => https://github.com/hexojs/site/pull/1470
- [x] https://github.com/hexojs/hexo/pull/4278 => https://github.com/hexojs/site/pull/1469
- [x] [release note](https://github.com/hexojs/hexo/pull/4423#issuecomment-659445911) => https://github.com/hexojs/hexo/pull/4423#issuecomment-659528100

## Pull request tasks

- [ ] Add test cases for the changes.
- [ ] Passed the CI test.

### CODE REVIEW

**Comment by SukkaW** [comment]
Also, the `_config.yml` of `hexo-starter` should be updated as well.

**Comment by YoshinoriN** [comment]
I notice some of the merged lists are deleted from [draft release](https://github.com/hexojs/hexo/releases).
It seems between `4.2.0 (2019-12-22)` and `4.2.1 (2020-05-17)` changes. They were exists certainly when I published `4.2.1`.

I assume, release-drafter overwrote them.
Sorry, it's my fault...

Now, I'm trying to generate merged list between `2019-12-22` and `2020-05-17`.
I will put it on this Issue and  [draft release](https://github.com/hexojs/hexo/releases).

---

Btw, I notice  [draft release](https://github.com/hexojs/hexo/releases) visibility is not public.
Other maintainers (`hexo/cores`) can see it?

**Comment by SukkaW** [comment]
> Other maintainers (hexo/cores) can see it?

@YoshinoriN Yes, at least I can see. So I suppose every hexojs team member can see it.

**Comment by SukkaW** [comment]
> I will put it on this Issue and [draft release](https://github.com/hexojs/hexo/releases).

@YoshinoriN 

You'd better backup it. Next time a commit come into the `master` branch, the `release drafter` will override your changes to Release Notes.

**Comment by SukkaW** [comment]
> Also, I put it on release draft :)

@YoshinoriN We could maintain the release note here since there are still 3 pending PR will be merged into `master` branch and `release drafter` will override the existed one.

**Comment by YoshinoriN** [comment]
> release drafter will override existed one.

I assume release-drafter will not override the current draft release.

When I published `4.2.1` I don't remember but probably created `4.3.0` draft release and wrote changes (between `4.2.0` and `4.2.1`) to `4.3.0` draft release.

After that release-drafter deleted `4.3.0`  and created `4.2.2`.

So, I think this problem caused by release-drafter settings problem. I think we should use `$NEXT_MINOR_VERSION` 
 instead of `[$NEXT_PATCH_VERSION]`(https://github.com/hexojs/hexo/blob/714e752edd70dc3fee38c88a13ba05c27bf01e87/.github/release-drafter.yml#L1). 🤔 

Anyway, thank you very much :)

**Comment by SukkaW** [comment]
A newer version of hexo-util has already be released, waiting for dependabot opening a new PR.

Also, after hexo-cli@4.0.0 is released, we should bump the version too.

Latest hexo-starter should be merged into hexo-cli@4.1.0 along with hexo@5.0.0.

**Comment by curbengh** [comment]
> hexo-util has already be released, waiting for dependabot opening a new PR.

It's a minor release and `^` won't trigger the dependabot. I will create PR to force update hexo-util in the npm cache.

**Comment by SukkaW** [comment]
@curbengh @stevenjoezhang I will rebase the PR after #4439 #4440 #4442 are merged.

**Comment by curbengh** [comment]
I would like to include https://github.com/hexojs/hexo/pull/4443 as well.

**Comment by SukkaW** [comment]
@curbengh @stevenjoezhang Rebased, and it is now ready for review.

**Comment by SukkaW** [comment]
@curbengh We could finish Changelog here before we adding a new GitHub release.

Also, I'd like to write a post at news introducing Hexo 5.0.0 changes in detail, so we only need to include basic information in changelog.

## Change Log (WIP)

### Features

- It is now possible install a theme through npm @SukkaW [#4112]

**Comment by SukkaW** [comment]
@hexojs/core Hey, we could add a `post install` message for inviting contributors.

**Comment by curbengh** [comment]
> we could add a `post install` message

I find `post install` message to be a bit bothersome. I prefer to have it on the website.

**Comment by SukkaW** [comment]
> you can create new release with that changelog, I'll edit it afterwards. I need some times for editing, don't want to delay the release.

draft release bot will automatically override any edited release note if a new commit push into `master` branch. That's why I maintain a release note here.

**Comment by curbengh** [comment]
I mean the changelog you attached is fine for publishing the release, once published, the bot won't touch it.

---

Pending dependabot to update hexo-cli@4 here.

**Comment by SukkaW** [comment]
> Pending dependabot to update hexo-cli@4 here.

Done.

**Comment by curbengh** [comment]
> we have to merge the documents' PR first

Merging...

**Comment by SukkaW** [comment]
@curbengh It is now ready for release.

**Comment by SukkaW** [comment]
> I mean the changelog you attached is fine for publishing the release, once published, the bot won't touch it.

@curbengh I have updated the change log with the drafted release. Hexo 5.0.0 is now ready to go.

**Comment by SukkaW** [comment]
@curbengh Would you mind publishing a newer version?

**Comment by curbengh** [comment]
I would like to include https://github.com/hexojs/hexo/issues/4446 in v5.

**Comment by SukkaW** [comment]
@curbengh Probably not. Injector is designed to insert "static" HTML only.

**Comment by noraj** [comment]
Thanks awesoem work. Soon a github release + git tag? https://github.com/hexojs/hexo/releases

**Comment by curbengh** [comment]
To confirm, this [changelog](https://github.com/hexojs/hexo/pull/4423#issuecomment-663856542) is the canonical one? I start from that?

**Comment by SukkaW** [comment]
> To confirm, this [changelog](https://github.com/hexojs/hexo/pull/4423#issuecomment-663856542) is the canonical one? I start from that?

The commit log since 4.2.0 can be foun here: https://github.com/hexojs/hexo/pull/4423#issuecomment-659528100

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo/releases/tag/5.0.0
https://www.npmjs.com/package/hexo/v/5.0.0

**Comment by SukkaW** [comment]
@hexojs/core https://github.com/hexojs/hexo-starter/pull/39 hexo-starter dependency update.

**Comment by curbengh** [comment]
@SukkaW I just noticed https://github.com/hexojs/hexo/pull/4046 hasn't been documented yet.
I can write for https://github.com/hexojs/hexo/pull/4185.

**Pull request merged**
