### PR TITLE
Fix error when tag.render <code>

### PR DESCRIPTION
**Pull request by popomore**

### CODE REVIEW

**Comment by popomore** [comment]
Same problem as https://github.com/hexojs/hexo/commit/2ba4e148b8bc159c7d014ae80d7f8f0e99f36dd8

**Comment by popomore** [comment]
It's broken in node7, can you retry it?

**Comment by popomore** [comment]
cc @NoahDragon

**Comment by NoahDragon** [comment]
Great, thank you for the PR. However, I don't clearly understand which scenario will cause the issue?

**Comment by popomore** [comment]
If I write nunjucks template in markdown like

```
`{{help.json()}}`
```

Hexo will render it as a nunjucks helper, so this pr will ignore this case

**Comment by NoahDragon** [comment]
Thanks. Make sense to me.

**Comment by NoahDragon** [comment]
@popomore Could you please have a look at this issue https://github.com/hexojs/hexo/issues/2563 ? Do you have any ideas to fix it?

**Comment by popomore** [comment]
It seems have been fixed?

**Comment by NoahDragon** [comment]
Actually, it's not. It's still under investigating, I'm not sure if it related to this PR.

**Comment by popomore** [comment]
#2568 has fixed it, the bug is just the greedy regexp, it should only match the content between the tag.

**Comment by seaoak** [comment]
@popomore Before your Pull Request #2461 was merged, `lib/extend/tag.js` escaped a `<code>` element only if it was the only child of a `<pre>` element.  Do you know the reason why we can not all `<code>` elements unconditionally?

**Comment by popomore** [comment]
@seaoak Hi, there two style is different in markdown. 

screenshot 2017-05-22 11 59 07
screenshot 2017-05-22 11 59 25

Sorry for the bug I made.

**Comment by NoahDragon** [comment]
@popomore No worries. I think the issue hides there for a long while, it is a good time to actually fix the code.

**Comment by lsdsjy** [comment]
https://github.com/hexojs/hexo/pull/2578#issuecomment-303488627

**Pull request merged**
