### PR TITLE
Add hour and minute for the post permalink.

### PR DESCRIPTION
**Pull request by felix-fly**
## What does it do?

Add hour and minute for the post permalink.

## How to test

Edit _config.yml file
```yml
permalink: :year/:month:day:hour:minute
```

## Pull request tasks

- [ ] Add test cases for the changes.
- [ ] Passed the CI test.

### CODE REVIEW

**Comment by felix-fly** [comment]
Can this be merged?

**Comment by tomap** [comment]
It looks good, but no unit tests?

**Comment by tomap** [comment]
https://github.com/hexojs/hexo/blob/master/test/scripts/filters/post_permalink.js#L84

Adding one does not seem complex, based upon existing ones

Can you do one, or do you need help?

```
it('post_title', () => {
    hexo.config.permalink = ':year/:month/:day/:hour/:minute/:post_title/';

    return Post.insert({
      source: 'sub/2015-05-06-my-new-post.md',
      slug: '2015-05-06-my-new-post',
      title: 'My New Post',
      date: moment('2015-05-06 12:13')
    }).then(post => {
      postPermalink(post).should.eql('2015/05/06/12/13/my-new-post/');
      hexo.config.permalink = PERMALINK;
      return Post.removeById(post._id);
    });
  });
```

That should be a start :)

**Comment by curbengh** [comment]
Just a note that when hour and minute is enabled,

```
permalink: :year/:month:day:hour:minute
```

but front-matter of a post doesn't have hour+minute, the permalink will default them to zero, e.g. "2015/05/06/00/00/my-new-post/".

**Comment by curbengh** [comment]
CI benchmark doesn't look great, but I believe it's more likely due to Travis is under heavy load (on weekend).

**Comment by SukkaW** [comment]
> CI benchmark doesn't look great, but I believe it's more likely due to Travis is under heavy load (on weekend).

@curbengh 
We might check https://www.traviscistatus.com/ and triger a rebuild when there are less `Active Linux Builds for Open Source projects`.

**Pull request merged**
