### PR TITLE
disable Nunjucks when the renderer spcify that

### PR DESCRIPTION
**Pull request by be5invis**
This PR adds Nunjucks disabling if the renderer claim that it can handle “tags” on its own.
Currently it is not active (i.e., Nunjucks would work) for all existing renderers.

### CODE REVIEW

**Comment by be5invis** [comment]
@NoahDragon Hold on.

**Comment by be5invis** [comment]
@NoahDragon Finish.

**Comment by NoahDragon** [comment]
IMO, give this decision to renderers is better than to the users. https://github.com/hexojs/hexo/pull/2478

**Comment by NoahDragon** [comment]
I'm thinking extend this function to post front matters. Instead of site-wide configuration variable, each post can disable Nunjucks when specified. Do you think this will be feasible and compatible with your change?

https://github.com/hexojs/hexo/issues/2622

**Comment by 9662** [comment]
Sorry, could you please provide an example of how would a renderer use this feature?

**Comment by be5invis** [comment]
@9662 
I have a custom renderer which is completely not MarkDown and Nunjucks notation may conflict with some of its inputs. That's (originally) why I created this PR.

**Pull request merged**
