### PR TITLE
fix: create post with a path composed of numbers throw an error

### LINKED ISSUE #4334: Create post with a path composed of numbers throw an error
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Expected behavior
It should be possible to create a post with a path using only numbers such as `404`.

## Actual behavior
```
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type number (404)
    at validateString (internal/validators.js:121:11)
    at join (path.js:1039:7)
    at Hexo.newPostPathFilter (/mnt/hdd/dev/blog/node_modules/hexo/lib/plugins/filter/new_post_path.js:37:18)
    at Hexo.tryCatcher (/mnt/hdd/dev/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/mnt/hdd/dev/blog/node_modules/bluebird/js/release/method.js:15:34)
    at /mnt/hdd/dev/blog/node_modules/hexo/lib/extend/filter.js:62:52
    at tryCatcher (/mnt/hdd/dev/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/mnt/hdd/dev/blog/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/mnt/hdd/dev/blog/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/mnt/hdd/dev/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/mnt/hdd/dev/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/mnt/hdd/dev/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/mnt/hdd/dev/blog/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/mnt/hdd/dev/blog/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/mnt/hdd/dev/blog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/mnt/hdd/dev/blog/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/mnt/hdd/dev/blog/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
```

## How to reproduce?

Run `hexo new page --path 404 "Page not found"`

## Environment & Settings

**Node.js & npm version**

```
Node v14.3.0
npm 6.14.5
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 /mnt/hdd/dev/blog
├── hexo@4.2.1
├── hexo-deployer-git@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@1.0.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-pug@1.0.0
├── hexo-renderer-stylus@1.1.0
└── hexo-server@1.0.0
```

**Your package.json `package.json`**
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "npm run clean && npm run build && hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.1"
  },
  "dependencies": {
    "hexo": "^4.2.1",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-pug": "^1.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  }
}
```

### PR DESCRIPTION
**Pull request by D-Sketon**
## What does it do?
 fix #4334

## Pull request tasks

- [x] Add test cases for the changes.
- [x] Passed the CI test.

### CODE REVIEW

**Comment by stevenjoezhang** [comment]
There will be an edge case: `--path 0x100` will become string `'256'`, not `'0x100'`. 

You can try to change the code here: https://github.com/hexojs/hexo-cli/blob/5c5fc8fe2fc781a557a30f1bf2043502825f173c/lib/hexo.ts#L18

```js
minimist(process.argv.slice(2), { string: ['_', 'p', 'path'] })
```
should work

**Comment by stevenjoezhang** [comment]
See also https://github.com/hexojs/hexo-cli/pull/200

**Comment by D-Sketon** [comment]
@stevenjoezhang should `slug` also be added to this code?
For example: `hexo new page --slug 0x404` will generate `1028.md`

**Comment by stevenjoezhang** [comment]
@D-Sketon Yes, the slug should also have a string type

**Comment by D-Sketon** [comment]
@stevenjoezhang  I'm a bit confused, do I just need to add extra test cases in this PR? How should they read the changes in hexo-cli and pass the test?

**Comment by stevenjoezhang** [comment]
It's tricky to cover this situation with unit tests, need to hook `process.argv` somehow

**Comment by D-Sketon** [comment]
Superseded by #5465

**Pull request closed without merging**
