### PR TITLE
support for multiple config files (#2210)

### PR DESCRIPTION
**Pull request by PirtleShell**
Give the `--config` flag support for multiple config files when generating or serving your site.

Inspired by Jekyll as suggested by @Lindsor in #2210.
## Usage

List the desired config files (JSON or YAML) in a comma-separated list (no spaces) after the config flag:

```
hexo server --config config1.yml,config2.json
```

This will combine all the config files and save the merged settings to `_multiconfig.yml`. The later values take precedence. It works with any number of JSON and YAML files with arbitrarily deep objects.

For instance, in the above example if `foo: bar` is in `config1.yml`, but `"foo": "dinosaur"` is in `config2.json`, `_multiconfig.yml` will contain `foo: dinosaur`.

### CODE REVIEW

**Comment by PirtleShell** [comment]
I'm unable to reproduce the appveyor errors on my machine with the same `node` and `npm` versions. This may be a Windows error? Can anyone confirm?

```bash
$ npm install
......
$ node -v
v0.12.16
$ npm -v
3.10.8
$ npm test
......
  812 passing (7s)
  7 pending
```

**Comment by NoahDragon** [comment]
I will take a look at it sometime later to see if I can reproduce the error..

**Comment by NoahDragon** [comment]
I think this issue is caused by the AppVoyer's user permission. It works fine on my computer.

image

We have to fix it before merging, otherwise, this error will repeat every time. 

Could you please try to fix it?

**Comment by PirtleShell** [comment]
I'll see what I can do tonight. In the tests, I check for appropriate warnings by reading the debug log, but it looks like Appveyor doesn't give itself permission to read that file... Thanks for looking into it!

**Comment by PirtleShell** [comment]
Well that's aggravating. The before all hook for the Console tests timed out so all its tests failed.

the failing tests

This PR does not affect the Console submodule. [These same tests passed in the previous commit](https://travis-ci.org/hexojs/hexo/jobs/169843022) and the only things that changed were some semicolons and new lines added to a test file that happens _after_ the console tests are run.

the previous commit before style edits

**Comment by NoahDragon** [comment]
Great work, LGTM.

**Comment by NoahDragon** [comment]
Tested and works well. Good job!

Usage suggestion:
1. Run `hexo g` with config file first;
2. Then run `hexo s` with config file accordingly.

E.g.
```
hexo g --config ./config1.yml ./config2.yml
hexo s --config ./config1.yml ./config2.yml 
```

**Pull request merged**
