### PR TITLE
include_code – add hljs option

### PR DESCRIPTION
**Pull request by Hiswe**
This PR is to align `include_code` with `code` options

- [ ] Add test cases for the changes <= no tests were defined for `code`
- [x] Passed the CI test.

### CODE REVIEW

**Comment by tcrowe** [comment]
Seems simple enough. What does that mean and what does it do?

Our PR template doesn't ask people to detail what it is doing or how to replicate it yet. Are you able to say how to replicate the issue?

Thank you @Hiswe !

**Comment by Hiswe** [comment]
## more on the issue

It's for having the **highlight.js** generated classes prefixed by `hljs-`

To handle that Hexo already supports the *hljs* option :

```yml
highlight:
  ...
  hljs: true
```
It's working fine on:

- [code block](https://hexo.io/docs/tag-plugins.html#Code-Block)
- [backtick code block](https://hexo.io/docs/tag-plugins.html#Backtick-Code-Block)

But the option is ignored in

- [include code](https://hexo.io/docs/tag-plugins.html#Include-Code)

This PR aim to have the same behavior across all those ways of rendering code.

## how to replicate

- in the `_config.yml` add the *hljs* option 
- in an article try to render 3 times the same code `<p>hello world!</p>` using:
```md

```html
<p>hello world!</p>
\```

{% codeblock lang:html %}
<p>hello world!</p>
{% endcodeblock %}

{% include_code lang:html path/to/file %}
```

The third one will be rendered without the highlight.js prefix

**Comment by tcrowe** [comment]
Thanks for the clarification, @Hiswe. I will test it now.

**Comment by tcrowe** [comment]
In trying to replicate the example I was not successful.

To setup my project I did:

```sh
mkdir hiswe-test
cd hiswe-test
hexo init
npm remove hexo
npm install Hiswe/hexo#include_code-highlight-options-fix
hexo serve --debug
```

`./source/_posts/hello-world.md`

```txt
---
title: Hello World
---

\```html
<p>hello world1!</p>
\```

{% codeblock lang:html %}
<p>hello world2!</p>
{% endcodeblock %}

{% include_code lang:js tmp.js %}
```

`./source/_posts/tmp.js`

```js
console.log('hello')
```

Example 1 and 2 displayed as expected. The one with `include_code` did not.

I don't think it's a problem with what you posted in this PR but I still can't successfully test it yet.

Any ideas to help me? Thank you @Hiswe

**Comment by Hiswe** [comment]
@tcrowe I've set up a git repo with the examples:

https://github.com/Hiswe/hexo-code-test

There is 2 branches:
- `hexo-master` using the current npm packge
- `hexo-code-fix` using my PR

Each branch has the same script `yarn start` which reinstall the `node_modules` and start an hexo server on different ports. 

for the `include-code`, in the first one I have the output

```html
<td class="code">
  <pre>
    <span class="line">
      <span class="tag">&lt;<span class="name">p</span>&gt;</span>
      hello world 3
      <span class="tag">&lt;/<span class="name">p</span>&gt;</span>
    </span>
    <br>
  </pre>
</td>
```

which render in:

no-hljs


in the second one

```html
<td class="code">
  <pre>
    <code class="hljs html">
      <span class="hljs-tag">&lt;<span class="hljs-name">p</span>&gt;</span>
      hello world 3
      <span class="hljs-tag">&lt;/<span class="hljs-name">p</span>&gt;</span>
      <br>
    </code>
  </pre>
</td>
```

which render in:

hljs

code isn't highlighted because the default CSS doesn't includes the right styles.

Maybe I should add test cases for the `filters/backtick_code_block.js` `tags/code` and `tags/include_code` in the PR… 

Hope it helps.

**Comment by Hiswe** [comment]
@JLHwung thanks :)

**Comment by tcrowe** [comment]
Thank you @Hiswe for providing more information so I could test it and for the contribution! It worked.

**Comment by Hiswe** [comment]
@tcrowe thanks for Hexo!

**Pull request merged**
