### PR TITLE
if post.title is empty, set it to post.slug

### PR DESCRIPTION
**Pull request by rupertqin**
## What does it do?
if post.title is empty, set it to post.slug

## How to test

```sh
git clone -b BRANCH https://github.com/USER/hexo.git
cd hexo
npm install
npm test
```

## Pull request tasks

- [ ] Add test cases for the changes.
- [ ] Passed the CI test.

### CODE REVIEW

**Comment by gautamz07** [comment]
@tcrowe @YoshinoriN any plans to merge this ?

**Comment by YoshinoriN** [comment]
@gautamz07 
I can't judge yet. Because I don't know what is contain `data.slug`.
And build is a failure.

**Comment by tcrowe** [comment]
It's not a bad idea to do that. If the source is changed and the tests are not run or changed it fails here: https://ci.appveyor.com/project/AbnerChou/hexo/builds/24483192/job/ym2citb826d8wrjp#L1909

**Comment by rupertqin** [comment]
I'v edit my code, and pass the test.

**Comment by rupertqin** [comment]
I'v edit my code, and pass the test. @YoshinoriN  @tcatche

**Comment by rupertqin** [comment]
ok, I would publish my own version Npm package

**Comment by stevenjoezhang** [comment]
posts without a title are considered to be a feature: https://github.com/hexojs/hexo-theme-unit-test/blob/master/source/_posts/no-title.md

**Pull request closed without merging**
