### PR TITLE
refactor(hexo): merge theme_config before generation

### LINKED ISSUE #3890: The proposal of installing theme through npm
The original discussion is at #2471 

Here is my proposal: 

1. We should not treat `hexo-theme-` prefixed package as a hexo plugin. See @tomap 's commit:  https://github.com/hexojs/hexo/compare/master...tomap:feature/themeAsPackagediff-3d0f701643104f3b0e388b8f6a9a7f3eR38
2. Users are still required to specify their theme's name in `_config.yml`, because...
3. Hexo will read `themes/[name]` directory first, then search `hexo-theme-[name]` directory under `node_modules`. It means the theme under `themes` directory should have higher priority. In this way no extra `theme_from_npm: true` configuration is needed. 
4. `theme_config` in `_config.yml` looks good, but it is better to have a separate theme config. We could introduce `_config.[name].yml`. Currently, `theme_config` has higher priority than `_config.yml` under theme directories. After bring up `_config.[name].yml`, I suggest the `theme_config in _config.yml > _config.[name].yml > _config.yml under theme directories` which will retain highest priority for `theme_config`.
5. ~~Also, we need to fix the issue that some plugins can not read theme config from `theme_config`: https://github.com/hexojs/hexo/issues/2471#issuecomment-557877081~~ 

IMHO, we could easily bring up this feature without any Breaking Changes: the theme structure, current configurations and setup will not be affected. Yes, I mean we can even bring up this feature during Hexo 4.x development.

cc @hexojs/core @jiangtj

### PR DESCRIPTION
**Pull request by SukkaW**
## What does it do?

#4120, https://github.com/hexojs/hexo/pull/4120#issuecomment-619574347, https://github.com/hexojs/hexo/issues/3890#issuecomment-644603994

This PR closes #3890.

## How to test

```sh
git clone -b theme_config_ctx https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

## Pull request tasks

- [x] Add test cases for the changes.
- [x] Passed the CI test.

### CODE REVIEW

**Comment by tomap** [comment]
Hi,

I'm not sure why you are moving the code? Is it done sooner with your code?
Or later?

Why?

**Comment by SukkaW** [comment]
@tomap Technically, sooner. `this._genterateLocals` build `Locals` in `this._generate`, while `this._generate` is called after `this.load`.

More details see https://github.com/hexojs/hexo/pull/4120#issuecomment-619574347 . @stevenjoezhang  want the plugin being able to read `config.theme_config` from `theme.config`.

**Comment by stevenjoezhang** [comment]
Yes, this is very important for theme developers. Otherwise additional code is needed to ensure that the configuration in `theme_config` is loaded correctly.
See also
https://github.com/theme-next/hexo-theme-next/commit/1b0b53a355184db65b2f19349c7b1372f1825174
https://github.com/theme-next/hexo-theme-next/blob/a7a948a08f48dbe48879e277703d75706aec18e5/scripts/events/lib/config.js#L34

**Comment by stevenjoezhang** [comment]
https://github.com/hexojs/hexo/blob/d1178192dbfb56469d2aa604c2ec67c9c957bfdc/lib/hexo/index.js#L304-L340

I confirm that this patch works fine with `hexo g`. However, in `hexo s` the `_generate` method is usually called by `watch` (line 325, 338), instead of `load` (line 312)
Is it possible to put the relevant code directly into the `_generate` method?

**Comment by SukkaW** [comment]
> Is it possible to put the relevant code directly into the `_generate` method?

Then any filter related with post rendering (like `before_post_render`) will be affected.

**Comment by curbengh** [comment]
> Merge theme config during watch() is now supported. Reloading the theme config is supported as well (see the test case added)

My test config:

_config.yml
``` yml
theme_config:
  foo:
    bar: 'bax'
```

theme's _config.yml

``` yml
foo:
  baz: 'bos'
```

article.ejs (to display theme config)
```
<%- JSON.stringify(theme.foo, null, 2) %>
```

---

In `hexo s`, after I change the value of `theme.foo.baz` in theme's _config.yml and reload the page, it crash with undefined property. No effect when changing `theme.foo.bar` in _config.yml, reloading the page doesn't show the updated value.

**Comment by SukkaW** [comment]
> Reloading the page doesn't show the updated value.

@curbengh It is expected behavior. Because site's `_config.yml` won't reload. Only theme's `_config.yml` will.

**Comment by SukkaW** [comment]
@curbengh Could you please re-verify reloading theme's config?

```bash
$ npm i sukkaw/hexo#theme_config_ctx
```

Then

```yaml
# _config.yml
theme_config:
  foo:
    bar: 'bax'
```

```yaml
# theme's _config.yml
foo:
  baz: 'bos'
```

Add following line to the theme template:

```ejs
<% console.log(theme.foo) %>
```

`hexo s` should output:

```
{ baz: 'bos', bar: 'bax' }
```

Update theme's config:

```yaml
# theme's _config.yml
foo:
  baz: 'box'
```

Then reload the page should output:

```
{ baz: 'box', bar: 'bax' }
```

**Comment by curbengh** [comment]
This time I tried showing everything inside `theme` object,

```
<% console.log(JSON.stringify(theme, null, 2)) %>
```

After I changed the `theme.foo.bar` in the theme's config and reload the page, the `theme` object is left with `theme.foo.bar` only.

**Comment by SukkaW** [comment]
@curbengh So it appears that it is not the issue if the PR though. We could dig into the watcher later.

Have you run unit test? Is it passed?

**Comment by curbengh** [comment]
I can confirm it's my machine's issue, not even downgrading to v3.9 helps. I recently migrate Ubuntu - Solus and I don't recall having this watch issue in Ubuntu. Anyway, I'll debug on my own, don't want to distract this PR.

Unit test passed on Node 12 & 14 in my machine. I still prefer to have a theme dev @stevenjoezhang to verify this PR.

**Comment by SukkaW** [comment]
@curbengh @stevenjoezhang 

I have added a test case, using `before_post_render`, `after_post_render`, `before_generate` filters to check if `theme.config` has been merged.

**Comment by jerryc127** [comment]
主題配置文件已經默認了一些配置
例如
item:
  - qq
  - wechat

我的_config.xxxxx.yml
更改配置
item:
  - twitter

結果 是生成 qq wechat twitter 
而不是我修改的 twitter

按道理 如果_config.xxxxx.yml配置已有 應該按照_config.xxxxx.yml的内容為准，因爲它優先性高.
這是本來設計就是這樣麽

**Comment by curbengh** [comment]
Priority is not relevant if a key doesn't have duplicate subkeys, they will be merged, not replaced.

``` yml
# themes/xxxx/_config.yml
item:
  lorem: 'a'
  ipsum: 'b'
```

``` yml
# _config.xxxx.yml
item:
  dolor: 'c'
```

``` js
console.log(theme.config)
item: {
  lorem: 'a',
  ipsum: 'b',
  dolor: 'c'
}
```

---

A subkey will only be replaced if there is duplicate:

``` yml
# themes/xxxx/_config.yml
item:
  lorem: 'a'
  ipsum: 'b'
```

``` yml
# _config.xxxx.yml
item:
  lorem: 'c'
```

``` js
console.log(theme.config)
item: {
  lorem: 'c',
  ipsum: 'b'
}
```

**Comment by jerryc127** [comment]
你这个举例 我明白
问题是我那例子属于subkey么
```
item:
  - qq
  - wechat
```

qq wechat 这个配置都是属于 item这个key的。 qq和wechat都是item 的值，就好比c是lorem的值，b是ipsum的值，
那这样 我的这个例子不是应该替换么。。

难道以 -xxx -xxx -xxx 这种形式赋值 都会被识别为几个subkey?

**Comment by curbengh** [comment]
In your example, `item` has array value. array value is merged.

``` js
const { deepMerge } = require('hexo-util')

const config = {
  theme_config: {
    item: ['a', 'b']
  }
}

const theme = {
  config: {
    item: ['c']
  }
}

theme.config = deepMerge(theme.config, config.theme_config);

console.log(theme.config)
// { item: [ 'c', 'a', 'b' ] }
```

---

If you want to replace the original `item`, you have to remove it.

**Comment by YunYouJun** [comment]
Why not [overwrite array](https://www.npmjs.com/package/deepmerge#arraymerge-example-overwrite-target-array) instead of [combine arrays](https://www.npmjs.com/package/deepmerge#arraymerge-example-combine-arrays)?

Is there any special reason? I think for themes, overwriting array is more suitable to providing some example configurations without disturbing the user.

Or just provide a configuration to decide whether to overwrite the array or merge the array?

**Pull request merged**
