### PR TITLE
expose `escape_html` helper method for string manipulation to templates

### PR DESCRIPTION
**Pull request by awwong1**
## What does it do?

Expose the `escape_html` utility function from [https://github.com/hexojs/hexo-util/blob/master/lib/escape_html.js](https://github.com/hexojs/hexo-util/blob/master/lib/escape_html.js) so it can be called in templates.

## How to test

Testing may not be necessary? Covered in [https://github.com/hexojs/hexo-util/blob/master/test/escape_html.spec.js](https://github.com/hexojs/hexo-util/blob/master/test/escape_html.spec.js) already.

Other `hexo-util` functions, like `strip_html`, `trim`, `titlecase`, `word_wrap`, `truncate` are untested.

## Pull request tasks

- [ ] Passed the CI test.

### CODE REVIEW

**Review by SukkaW — APPROVED** [review]
LGTM!

**Review by SukkaW — CHANGES_REQUESTED** [review]
Well, would you mind adding unit tests?

**Comment by awwong1** [comment]
> Well, would you mind adding unit tests?

@SukkaW Sure, I can add them if you feel it is necessary.
The unit tests will basically be ports of these for the relevant exposed functions: https://github.com/hexojs/hexo-util/tree/master/test

**Comment by SukkaW** [comment]
> Sure, I can add them if you feel it is necessary.

@awwong1 

`escapeHTML` has its own test cases in hexo-util, thus a simple test case in `hexo` will be fine (it is used to improve the test coverage, which is calculated by how many lines of the code being executed during the test).

**Review by SukkaW — APPROVED** [review]

**Comment by Android-KitKat** [comment]
Nice! `escape_html` is very useful in templates.

**Comment by SukkaW** [comment]
> eg: Generate HTML Attribute.

@Android-KitKat 

That is very useful. But for now (since Hexo won't release a new version very soon), you can implement the helper by your self through Hexo API:

```js
// escape_html_helper.js
const { escapeHTML } = require('hexo-util');
hexo.extend.helper.register('escape_html', (str) =>  escapeHTML(str));
```

And put the file under your theme's `scripts` directory. This actually registers a helper with the name `escapa_html`. With the file, you can use `escape_html` in your theme right now (without waiting for a newer version of Hexo).

**Pull request merged**
