### PR TITLE
Opengraph support for twitter player (video content)

### PR DESCRIPTION
**Pull request by giuseppelt**

### CODE REVIEW

**Comment by Xuanwo** [comment]
Please upodate the test at the same time.

**Comment by giuseppelt** [comment]
bump

**Comment by giuseppelt** [comment]
hey, what's going on?

**Comment by NoahDragon** [comment]
It's auto close by the Stale bot. As Xuanwo has continued on another journey. I will review the change. If everything works well, the change could be in the next build.

**Comment by NoahDragon** [comment]
Could you please fix the error in travis-ci?

**Comment by giuseppelt** [comment]
@NoahDragon I fixed the test, the jscs issue I can't do nothing about

**Comment by JLHwung** [comment]
@giuseppelt Could you please fix the jscs errors and rebase on the latest master branch? Thank you.

**Comment by stevenjoezhang** [comment]
Any updates on this thread?

**Review by botreview — APPROVED** [review]
LGTM

**Pull request closed without merging**
