### PR TITLE
add timestamp for post data

### PR DESCRIPTION
**Pull request by tangkunyin**
In order to use timestamp in permalink. Timestamp var need to be added in post data.

This PR have done these things.

Hope to be merged. Thank you

### CODE REVIEW

**Comment by tcrowe** [comment]
I was looking at this: https://hexo.io/docs/configuration.html#URL

Does this PR enable something like `permalink: :timestamp/:title/`?

**Comment by tangkunyin** [comment]
@tcrowe Yes. This PR will make timestamp more convenient when you are using a DIY permalink

**Comment by tcrowe** [comment]
If I run the tests on this branch it's not expecting the `timestamp`

**Comment by tcrowe** [comment]
I've gotta run so I'll check back later

It may be better like this:

```diff
diff --git a/lib/hexo/post.js b/lib/hexo/post.js
index 5bab642e..f700a226 100644
--- a/lib/hexo/post.js
+++ b/lib/hexo/post.js
@@ -59,7 +59,10 @@ Post.prototype.create = function(data, replace, callback) {
   data.slug = slugize((data.slug || data.title).toString(), {transform: config.filename_case});
   data.layout = (data.layout || config.default_layout).toLowerCase();
   data.date = data.date ? moment(data.date) : moment();
-  data.timestamp = moment().unix();
+
+  if (data.timestamp !== undefined) {
+    data.timestamp = moment().unix();
+  }
 
   return Promise.all([
     // Get the post path
diff --git a/lib/hexo/scaffold.js b/lib/hexo/scaffold.js
index 4e99816e..46c73fb9 100644
--- a/lib/hexo/scaffold.js
+++ b/lib/hexo/scaffold.js
@@ -14,7 +14,6 @@ Scaffold.prototype.defaults = {
     'layout: {{ layout }}',
     'title: {{ title }}',
     'date: {{ date }}',
-    'timestamp: {{ timestamp }}',
     'tags:',
     '---'
   ].join('\n')
diff --git a/test/scripts/filters/post_permalink.js b/test/scripts/filters/post_permalink.js
index f663d46f..3d472e88 100644
--- a/test/scripts/filters/post_permalink.js
+++ b/test/scripts/filters/post_permalink.js
@@ -94,4 +94,21 @@ describe('post_permalink', () => {
       return Post.removeById(post._id);
     });
   });
+
+  it('title timestamp permalink', () => {
+    var unixTime = moment().unix();
+    var slug = 'my-new-post';
+    hexo.config.permalink = ':timestamp/:title';
+    return Post.insert({
+      source: 'sub/2015-05-06-my-new-post.md',
+      title: 'My New Post',
+      slug,
+      date: moment('2015-05-06'),
+      timestamp: unixTime
+    }).then(post => {
+      postPermalink(post).should.eql(`${unixTime}/${slug}`);
+      hexo.config.permalink = PERMALINK;
+      return Post.removeById(post._id);
+    });
+  });
 });
```

**Comment by tcrowe** [comment]
That enabled me to run the tests successfully

**Comment by tcrowe** [comment]
Next we should look for the right field name. `unixTimestamp` or `timestamp` because another type of timestamp data field comes from `Date.now()`

**Comment by tcrowe** [comment]
Documentation that would need to be updated if we commit this:
+ [ ] https://hexo.io/docs/configuration.html#URL
+ [ ] https://hexo.io/docs/front-matter.html#Settings-amp-Their-Default-Values
+ [ ] https://hexo.io/docs/permalinks.html#Variables

**Comment by tangkunyin** [comment]
@tcrowe Very nice

**Pull request closed without merging**
