### PR TITLE
Fix code quality issues

### PR DESCRIPTION
**Pull request by withshubh**
[DeepSource](https://deepsource.io/) is a code review automation tool that detects code quality issues and helps you to automatically fix some of them. You can use DeepSource to track test coverage, Detect problems in Dockerfiles, etc. in addition to detecting issues in code. 

All the features of the DeepSource are mentioned [here](https://deepsource.io/features/).
I'd suggest you integrate DeepSource since it is free for Open Source projects forever.

### Using DeepSource to continuously analyze your repository

- Merge this PR. I have included a `.deepsource.toml` in this PR, which you can use to configure your analysis settings.
- Install DeepSource on your repository [here](https://deepsource.io/signup).
- Activate analysis [here](https://deepsource.io/gh/hexojs/hexo/).

### CODE REVIEW

**Comment by SukkaW** [comment]
Thanks for your contribution!

Although DeepSource looks very promising but **personally** I don't think hexojs could benefit more from DeepSource.

We already use ESLint to make sure the code quality will not be compromised. Currently, we are using GitHub Action to check every commit with ESLint (So we do have continuous analysis, see #4143). And we use `mochajs` for unit tests and coverage, and we are using [coverall](https://coveralls.io/) for coverage reports.

Would you mind give us an introduction about how hexojs could utilize DeepSource for better code quality management?

**Comment by withshubh** [comment]
> Thanks for your contribution!
> 
> Although DeepSource looks very promising but **personally** I don't think hexojs could benefit more from DeepSource.
> 
> We already use ESLint to make sure the code quality will not be compromised. Currently, we are using GitHub Action to check every commit with ESLint (So we do have continuous analysis, see #4143). And we use `mochajs` for unit tests and coverage, and we are using [coverall](https://coveralls.io/) for coverage reports.
> 
> Would you mind give us an introduction about how hexojs could utilize DeepSource for better code quality management?

Hi @SukkaW :wave: 

DeepSource works as an additional service (just like Codacy, etc.) that you don’t have to run yourself. The scope of what you can do is also more than one programming language: for instance, you can use DeepSource to track test coverage, detect problems in Dockerfiles, etc. in addition to detecting issues in JavaScript. 
The DeepSource JavaScript analyzer fully supports all the ESLint core JavaScript rules. Along with that, it also currently supports a few ESLint [plugins](https://deepsource.io/docs/analyzer/javascript.html#eslint-rules-plugins). DeepSource also internally uses the popular JavaScript [style guides](https://deepsource.io/docs/analyzer/javascript.html#style-guide) and code formatters like Prettier and StandardJS.

**Review by botreview — APPROVED** [review]
LGTM

**Comment by withshubh** [comment]
@SukkaW

And Yes, DeepSource is free forever for Open Source :sparkling_heart:

**Comment by withshubh** [comment]
Hi @SukkaW :wave: 

Any thought of activating DeepSource on this repo and fixing the issues?

**Pull request closed without merging**
